config/routes.rb
Rails.application.routes.draw do
	root to: 'tags#home'
	get '/' => 'tags#home'
	get '/tags' => 'tags#index'
	get '/tags/:id' => 'tags#show', as: :tag
	get 'destinations/:id' => 'destinations#show', as: :destination

	get '/destinations/:id/edit' => 'destinations#edit', as: :edit_destination 
	patch '/destinations/:id' => 'destinations#update'
end

app/models/destination.rb
class Destination < ActiveRecord::Base
	belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :destinations 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
	def show
	    @destination = Destination.find(params[:id])
	end

	def edit
		@destination = Destination.find(params[:id])
	end

	def update 
	  @destination = Destination.find(params[:id]) 
	  if @destination.update_attributes(destination_params) 
	    redirect_to(:action => 'show', :id => @destination.id) 
	  else 
	    render 'edit' 
	  end 
	end

	private 
  	def destination_params 
    	params.require(:destination).permit(:name, :description) 
  	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
		@tags = Tag.all
		@tag = Tag.find(params[:id])
	end

	def show 
	  	@tag = Tag.find(params[:id]) 
	  	@destinations = @tag.destinations 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/destinations/edit.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="destination">
  <div class="container">
    <%= image_tag @destination.image %>
    
    <!-- Your code here -->
    <%= form_for(@destination) do |f| %>
      <%= f.text_field :name %>
      <%= f.text_field :description %>
      <%= f.submit "Update", :class => "btn" %>
    <% end %> 

  </div>
</div> 

app/views/destinations/show.html.erb
<body class="destination_body">
  <div class="show_header">
      <p><%= @destination.name %></p>
  </div>

  <hr>
  <hr>

  <div class="destination">
    <div class="container">
      <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8 destination_card">
          <%= image_tag @destination.image %>
          <p class="destination_title">Description: </br></br> <%= @destination.description %></p>
        </div>
        <div class="col-lg-2"></div>
      </div>
    </div>
  </div> 
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Surfing's Best</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Dosis:700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Original+Surfer' rel='stylesheet' type='text/css'>
  <link rel="icon" href="https://d30y9cdsu7xlg0.cloudfront.net/png/19379-200.png">
</head>
<body>

	<%= yield %>

</body>
</html>

app/views/tags/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body class="home">
	<div class="row home_box">
		<div class="col-lg-3"></div>
		<div id="box1" class="col-lg-6 box">
			<div class="row col-lg-12">
				<div class="first col-lg-12">Welcome To Surfing's Best!</div>


				<a href="<%= tag_path(1) %>" class="opening_button">Check Breaks</a>

			</div>
		</div>
		<div class="col-lg-3"></div>
	</div>
</body>
</html>

app/views/tags/index.html.erb
<div class="row header">
  <div class="col-lg-1"></div>
  <div class="col-lg-1">
    <img src="http://papagayosports.com/wp-content/uploads/2015/11/surf-icon-small.png">
  </div>
  <div class="col-lg-6">
    <h1>Secret Spot Reviews</h1>
  </div>
</div>

<div class="tags">
  <div class="container">
    <div class="cards row">
    	<% @tags.each do |t| %>
      <div class="card col-xs-4">
        <%= image_tag t.image %>
        <h2><%= t.title %></h2>
        <%= link_to "Learn more", tag_path(t) %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tags/show.html.erb
<body class="show_body">
  <div class="header">
    <div class="container">
      <img src="http://papagayosports.com/wp-content/uploads/2015/11/surf-icon-small.png"> Surfing's Best
    </div>
  </div>

  <div class="tag">
    <div class="container">
    <hr>
    <hr>

      <div class="cards row">
        <% @destinations.order("name").each do |d| %>
        <div class="card col-lg-4 col-xs-4">
          <%= image_tag d.image %>
          <h2><%= d.name %></h2>
          <p><%= link_to "Read more", destination_path(d) %></p>
        </div>
        <% end %>
      </div>

    </div>
  </div>
</body>